// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    APlayer: typeof import('./../../src/components/audio/APlayer.vue')['default']
    ArticleList: typeof import('./../../src/components/common/articleList/articleList.vue')['default']
    AudioHistoryList: typeof import('./../../src/components/common/audioList/audioHistoryList.vue')['default']
    CollectList: typeof import('./../../src/components/common/collectList/collectList.vue')['default']
    Dialog: typeof import('./../../src/components/common/dialog/Dialog.vue')['default']
    Editor: typeof import('./../../src/components/editor/Editor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InfoLayout: typeof import('./../../src/components/common/infoLayout/infoLayout.vue')['default']
    Layout: typeof import('./../../src/components/layout/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MyComp: typeof import('./../../src/components/common/myComp/myComp.vue')['default']
    Particles: typeof import('./../../src/components/particles/index.vue')['default']
    Progress: typeof import('./../../src/components/common/progress/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./../../src/components/common/tab/Tab.vue')['default']
    TabbarAside: typeof import('./../../src/components/layout/comps/tabbarAside.vue')['default']
    Tabs: typeof import('./../../src/components/common/tabs/Tabs.vue')['default']
    TimeComp: typeof import('./../../src/components/common/timeComp/timeComp.vue')['default']
    UserHeader: typeof import('./../../src/components/layout/users/userHeader.vue')['default']
  }
}

export { }
