// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    APlayer: typeof import('./../../src/components/audio/APlayer.vue')['default']
    ArticleList: typeof import('./../../src/components/common/articleList/articleList.vue')['default']
    CollectList: typeof import('./../../src/components/common/collectList/collectList.vue')['default']
    Dialog: typeof import('./../../src/components/common/dialog/Dialog.vue')['default']
    Editor: typeof import('./../../src/components/editor/Editor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    InfoLayout: typeof import('./../../src/components/common/infoLayout/infoLayout.vue')['default']
    Layout: typeof import('./../../src/components/layout/index.vue')['default']
    MyComp: typeof import('./../../src/components/common/myComp/myComp.vue')['default']
    Particles: typeof import('./../../src/components/particles/index.vue')['default']
    Progress: typeof import('./../../src/components/common/progress/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./../../src/components/common/tab/Tab.vue')['default']
    TabbarAside: typeof import('./../../src/components/layout/comps/tabbarAside.vue')['default']
    TimeComp: typeof import('./../../src/components/common/timeComp/timeComp.vue')['default']
    UserHeader: typeof import('./../../src/components/layout/users/userHeader.vue')['default']
  }
}

export { }
